### ISSUE TITLE
Stock data

### ISSUE THREAD

**Issue by johnfren** [benjamincham/freeoptionschain#1]
Hello! Can you make the same thing with the options data, but with stocks instead?

**Comment by benjamincham** [comment]
hi there, thanks for the feature request. 

Yes, i think it is a great feature to have and i would be able to first integrate real-time stock quotes. 

Then i would provide an API to provide streaming capabilities via function callback

**Comment by johnfren** [comment]
Sounds great, can't wait to try it! Will this feature be limited to certain stocks/markets or will there be option to chose on your own?

**Comment by benjamincham** [comment]
i have release an API to fetch stock price in real time. I would implement streaming function in the next release.

please update to the package, do let me know if you encounter the any issues/error
'pip install --upgrade freeoptionschain '
