### ISSUE TITLE
FOC.db is missing

### ISSUE THREAD

**Issue by snas1690** [benjamincham/freeoptionschain#3]
Completed all requirements but getting this error

>>> import FOC
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\FOC\__init__.py", line 2, in <module>
    from .db import *
ModuleNotFoundError: No module named 'FOC.db'

**Comment by benjamincham** [comment]
It seems like there might be an issue with the way you have imported and call the package.

please refer to [demo.py](https://github.com/benjamincham/freeoptionschain/blob/main/demo.py) on how you should import and use the library

**Comment by benjamincham** [comment]
mark close

**Comment by lym-afla** [comment]
I have got the same issue.

It seems the problem is in 'from .db import *' line in main.py. There is no db.py in FOC folder.

**Comment by benjamincham** [comment]
please refer to [demo.py](https://github.com/benjamincham/freeoptionschain/blob/main/demo.py) on how you should import and use the library

**Comment by snas1690** [comment]
from FOC import FOC
Traceback (most recent call last):
See below, imported exactly as in demo.py. Still getting the same issue.

  File "<ipython-input-6-129d4d61e16d>", line 1, in <module>
    from FOC import FOC

  File "C:\ProgramData\Anaconda3\lib\site-packages\FOC\__init__.py", line 2, in <module>
    from .db import *

ModuleNotFoundError: No module named 'FOC.db'

**Comment by snas1690** [comment]
from FOC import FOC
Traceback (most recent call last):

  File "<ipython-input-6-129d4d61e16d>", line 1, in <module>
    from FOC import FOC

  File "C:\ProgramData\Anaconda3\lib\site-packages\FOC\__init__.py", line 2, in <module>
    from .db import *

ModuleNotFoundError: No module named 'FOC.db'

**Comment by benjamincham** [comment]
may i check what is the python version you are using?

**Comment by benjamincham** [comment]
i have release version:0.01

please update the package, do let me know if you still encounter the same error
`pip install --upgrade freeoptionschain
`

Thanks!

**Comment by snas1690** [comment]
(base) PS C:\Windows\system32> python --version
Python 3.7.6

upgraded. Still have issue, see below

(base) PS C:\Windows\system32> python
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from FOC import FOC
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\FOC\__init__.py", line 2, in <module>
    from .db import *
ModuleNotFoundError: No module named 'FOC.db'

**Comment by benjamincham** [comment]
thanks for sharing the info, i'll check it out on a PC with windows OS. 

I'll reopen the issue as a bug fix

**Comment by snas1690** [comment]
Thanks a lot!

**Comment by jfitz001** [comment]
Hi there, I think the commit is just missing the db.py file.

**Comment by benjamincham** [comment]
i have tried it on my windows PC,using anaconda with python=3.8
I did not encounter any error, please see my screenshot

![image](https://github.com/benjamincham/freeoptionschain/assets/34295582/cec29e98-6658-4a0d-bb20-5bce9b94420d)

**Comment by benjamincham** [comment]
i found out the reason for the error was because i did not provide the cython-compiled db library that is compatible for windows OS. 

i have updated the repository with 'db.cp38-win_amd64.pyd', please update the package, do let me know if you still encounter the same error
`pip install freeoptionschain==0.2`
